server:
    port: 8088
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
      


spring:

    mustache:
      charset: UTF-8
      content-type: text/html; charset=utf-8
      prefix: classpath:/templates/
      suffix: .html

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
        username: user
        password: user

    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create
            naming: 
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            use-new-id-generator-mappings: false
        show-sql: true
        properties:
            hibernate.format_sql: true

    jackson:
        serialization:
            fail-on-empty-beans: false
